{{- if and (not .Values.blueGreen.enabled) (not .Values.canary.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    project: secure-mlops
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollback.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.rollback.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollback.maxSurge }}
      maxUnavailable: {{ .Values.rollback.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-api
      automountServiceAccountToken: false
      containers:
        - name: mlops-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.health.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.health.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.readiness.periodSeconds }}
          {{- if .Values.secrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.drift.enabled }}
            - name: PREDICTION_LOG_DIR
              value: "/data/predictions"
          volumeMounts:
            - name: prediction-data
              mountPath: /data/predictions
            {{- end }}
      {{- if .Values.drift.enabled }}
      volumes:
        - name: prediction-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-prediction-data
      {{- end }}
{{- end }}
