{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
    app: {{ .Release.Name }}-api
    project: secure-mlops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    {{- if .Values.canary.enabled }}
    name: {{ .Release.Name }}-stable
    {{- else if .Values.blueGreen.enabled }}
    name: {{ .Release.Name }}-{{ .Values.blueGreen.activeSlot }}
    {{- else }}
    name: {{ .Release.Name }}-api
    {{- end }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUpStabilization }}
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDownStabilization }}
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
    {{- if .Values.autoscaling.customMetrics.enabled }}
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "{{ .Values.autoscaling.customMetrics.targetRequestRate }}"
    {{- end }}
{{- end }}
