all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    project_root: "{{ playbook_dir }}/../../"
    minikube_cpus: 2
    minikube_memory: 4096
    minikube_driver: docker
    k8s_namespace: default
    helm_release_name: securemlops
    docker_image_name: secure-mlops-api
    docker_image_tag: v1
